class Init():
    driver = '/usr/local/bin/chromedriver'
    driverFirefox = '/usr/local/bin/geckodriver'
    driverSafari = '/usr/local/bin/safaridriver'
    url1 = 'http://testautomationpractice.blogspot.com/'
    url2 = 'https://www.selenium.dev/selenium/docs/api/java/'
    url3 = 'https://www.expedia.com/'
    url4 = 'https://web.drivezytest.com'
    url5 = 'http://newtours.demoaut.com/'
    url6 = 'http://demo.automationtesting.in/Windows.html'
    url7 = 'file:///Users/govind794/Desktop/test.html'
    url8 = 'http://www.mnnit.ac.in/index.php/academic/90-academic-portal'
    url9 = 'https://admin.drivezytest.com/'
    url10 = 'http://demo.automationtesting.in/FileDownload.html'
    url11 = 'https://www.amazon.in/'
    username = 'govind.patidar@drivezy.com'
    password = 'Brother794@'
